services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  db:
    image: postgres:15
    container_name: fraud_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fraud_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - mongo
      - redis
      - rabbitmq

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: worker_service
    command: python3 worker.py
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "3000:80"
    depends_on:
      - backend

  mcp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fraud-detection-system-mcp
    command: uvicorn mcp.server:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo

volumes:
  mongodb_data: